name: Compile

on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3

      - name: install dependencies
        run: sudo apt install -y nasm clang mtools

      - name: install zig
        run: sudo snap install zig --classic --beta

      - name: versions
        run: |
          clang --version
          ld --version

      - name: make
        run: CC=clang make
