name: Compile

on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3

      - name: install dependencies
        run: sudo apt install -y nasm gcc-11

      - name: versions
        run: |
          gcc --version
          gcc-11 --version
          ld --version

      - name: make
        run: CC=gcc-11 make
